"""Initial Database Migration

Revision ID: 1f6720803d3d
Revises: 
Create Date: 2019-03-05 09:20:30.727779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6720803d3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schoolname', sa.Text(length=128), nullable=True),
    sa.Column('coachname', sa.Text(length=128), nullable=True),
    sa.Column('registrationfee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member', sa.Text(length=128), nullable=True),
    sa.Column('sch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sch_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('schools')
    # ### end Alembic commands ###
